@echo off
echo Starting Market Manager...
echo.
echo 1. Starting React development server...
start cmd /k "cd /d %~dp0 && npm start"
echo.
echo 2. Waiting for React server to start...
timeout /t 10 /nobreak > nul
echo.
echo 3. Starting Electron app...
start cmd /k "cd /d %~dp0 && npm run electron"
echo.
echo Market Manager is starting...
echo Check the opened windows for the application.
pause
